comptime ARRAY_LAYER_COUNT_UNDEFINED = UInt32.MAX


comptime COPY_STRIDE_UNDEFINED = UInt32.MAX


comptime DEPTH_SLICE_UNDEFINED = UInt32.MAX


comptime LIMIT_U32_UNDEFINED = UInt32.MAX


comptime LIMIT_U64_UNDEFINED = UInt64.MAX


comptime MIP_LEVEL_COUNT_UNDEFINED = UInt32.MAX


comptime QUERY_SET_INDEX_UNDEFINED = UInt32.MAX


comptime WHOLE_MAP_SIZE = Int.MAX


comptime WHOLE_SIZE = UInt64.MAX
