alias ARRAY_LAYER_COUNT_UNDEFINED = UInt32.MAX


alias COPY_STRIDE_UNDEFINED = UInt32.MAX


alias DEPTH_SLICE_UNDEFINED = UInt32.MAX


alias LIMIT_U32_UNDEFINED = UInt32.MAX


alias LIMIT_U64_UNDEFINED = UInt64.MAX


alias MIP_LEVEL_COUNT_UNDEFINED = UInt32.MAX


alias QUERY_SET_INDEX_UNDEFINED = UInt32.MAX


alias WHOLE_MAP_SIZE = Int.MAX


alias WHOLE_SIZE = UInt64.MAX
