[workspace]
authors = ["Lukas Hermann"]
platforms = ["osx-arm64"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
preview = ["pixi-build"]

[package]
name = "wgpu-mojo"
version = "0.1.0"
description = "WebGPU bindings for Mojo"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[dependencies]
mojo = ">=0.25.7.0.dev2025110305,<0.26"
max = ">=25.7.0.dev2025110305,<26"
glfw-mojo = { git = "https://github.com/lsh/glfw-mojo" }

[tasks]
gen = "python gen_c.py webgpu.json && mojo format wgpu"
