[workspace]
authors = ["Lukas Hermann"]
platforms = ["osx-arm64"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
preview = ["pixi-build"]

[dependencies]
mojo = ">=0.25.7.0.dev2025110305,<0.26"
max = ">=25.7.0.dev2025110305,<26"
glfw = ">=3.4,<4"
glfw-mojo = { git = "https://github.com/lsh/glfw-mojo" }
wgpu-native = ">=22.1.0,<23"

[tasks]
setup = { cmd = "mkdir -p build" }
build = { cmd = "mojo build main.mojo -o build/main", depends-on = ["setup"] }
fix-rpath = """
install_name_tool -change \
  /Users/runner/miniforge3/conda-bld/wgpu-native_1730778338515/work/target/aarch64-apple-darwin/release/deps/libwgpu_native.dylib \
  @rpath/libwgpu_native.dylib \
  build/main && \
install_name_tool -add_rpath @loader_path/../.pixi/envs/default/lib build/main
"""
exec = { cmd = "./build/main", depends-on = ["build", "fix-rpath"] }
gen = "python gen_c.py webgpu.json && mojo format wgpu"

[activation.env]
MODULAR_MOJO_MAX_SYSTEM_LIBS = "-lm,-L$CONDA_PREFIX/lib,-lglfw,-lwgpu_native"
